<a href="https://colab.research.google.com/github/nicovakr/Pytorch-init/blob/master/pytorch_init.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch for Deep Learning

In [5]:
import torch
import torchvision
import torchaudio

In [31]:
import numpy as np

# PyTorch Basics : Tensors and Gradients

## Tensor : number, vector, matrix, or any n-dimensional array.

In [7]:
#entry is a number
t1 = torch.tensor(4.)
t1, t1.dtype

(tensor(4.), torch.float32)

In [8]:
#entry is a list/vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [9]:
#entry is a matrix
t3 = torch.tensor([[5,6], [7,8], [9,10]]) 
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [10]:
#entry is a 3D array
t4 = torch.tensor([[[11, 12, 13],[13, 14, 15]],  
                   [[15, 16, 17],[17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [11]:
#t1 : nombre
#t2 : longueur vector
#t3 : shape ligne, colonne
#t4 : shape prof, ligne, colonne
t1.shape, t2.shape, t3.shape, t4.shape

(torch.Size([]), torch.Size([4]), torch.Size([3, 2]), torch.Size([2, 2, 3]))

## Tensor operations and gradients

In [27]:
#create tensors with requires_grad = True or not
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [28]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [29]:
#compute derivaties
y.backward() 

PyTorch permet de calculer des derivees par rapport aux tensors avec 'requires_grad' = True (called autograd).

In [30]:
#partial derivaties :
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad) # y = x*w+b -> y'/db = 1

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [32]:
#create a tensor with a fixed value for every element
t6 = torch.full((3,2), 23)
t6

tensor([[23, 23],
        [23, 23],
        [23, 23]])

In [33]:
#concatenate two tensors with compatibles shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [23, 23],
        [23, 23],
        [23, 23]])

In [39]:
#compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.8462, -0.8462],
        [-0.8462, -0.8462],
        [-0.8462, -0.8462]])

In [40]:
#change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.8462, -0.8462]],

        [[-0.8462, -0.8462],
         [-0.8462, -0.8462]]])

# Interoperability with Numpy

In [41]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [45]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
#y = torch.tensor(x) : this method create a copy of x
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [46]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [47]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])